import type { ProductSnapshot } from './types';

export const emptyProductSnapshot: ProductSnapshot = Object.freeze({
  generation: 0,
  sequence: 0,
  connection: 'restoring',
  providers: [],
  workspace: null,
  sessions: [],
  activeSessionId: null,
  messages: [],
  turnStatus: 'idle',
  queue: [],
  activity: [],
  approvals: [],
  changes: [],
  diagnostics: [],
  resources: [],
  update: {
    status: 'disabled' as const,
    endpointConfigured: false,
    publicKeyConfigured: false,
    message:
      'Public updates are disabled until release hosting and a verification key are configured.',
  },
});

export const productFixture: ProductSnapshot = Object.freeze({
  generation: 1,
  sequence: 18,
  connection: 'ready',
  providers: [
    {
      id: 'openai-codex',
      name: 'ChatGPT / Codex',
      detail: 'Use an existing ChatGPT Plus or Pro subscription.',
      accountLabel: 'Connected subscription',
      connected: true,
      methods: [
        {
          id: 'subscription',
          label: 'Continue with ChatGPT / Codex',
          classification: 'recommended',
        },
        { id: 'api-key', label: 'Use an API key instead', classification: 'fallback' },
      ],
      models: [
        { id: 'gpt-5.6', name: 'GPT-5.6', reasoning: true, acceptsImages: true },
        { id: 'gpt-5.4-mini', name: 'GPT-5.4 mini', reasoning: true, acceptsImages: true },
      ],
    },
    {
      id: 'anthropic-claude',
      name: 'Claude',
      detail: 'Use an existing Claude Pro or Max subscription.',
      connected: false,
      methods: [
        { id: 'subscription', label: 'Continue with Claude', classification: 'recommended' },
        { id: 'api-key', label: 'Use an API key instead', classification: 'fallback' },
      ],
      models: [
        { id: 'claude-opus-4.1', name: 'Claude Opus 4.1', reasoning: true, acceptsImages: true },
        {
          id: 'claude-sonnet-4.1',
          name: 'Claude Sonnet 4.1',
          reasoning: true,
          acceptsImages: true,
        },
      ],
    },
  ],
  workspace: {
    capabilityId: 'workspace-5bb349af3dd341cf',
    name: 'PIUI',
    displayPath: 'Documents / Code / PIUI',
    trust: 'trusted',
    lastOpenedAt: 'Today, 9:41 am',
  },
  sessions: [
    {
      id: 'session-current',
      generation: 4,
      title: 'Finish the desktop experience',
      project: 'PIUI',
      updatedAt: 'Just now',
      status: 'active',
      branch: 'main',
      preview: 'Complete the product shell, workflows and release checks.',
    },
    {
      id: 'session-architecture',
      generation: 2,
      title: 'Architecture gate',
      project: 'PIUI',
      updatedAt: 'Yesterday',
      status: 'complete',
      preview: 'Proved the private sidecar, credentials and approval boundary.',
    },
    {
      id: 'session-onboarding',
      generation: 1,
      title: 'Onboarding copy review',
      project: 'PIUI',
      updatedAt: '31 July',
      status: 'branched',
      branch: 'onboarding',
      preview: 'Refined subscription-first provider language.',
    },
  ],
  activeSessionId: 'session-current',
  messages: [
    {
      id: 'message-1',
      role: 'user',
      author: 'You',
      timestamp: '9:38 am',
      status: 'stable',
      markdown:
        'Continue building the full PIUI desktop experience. Keep the interface calm, clear and local-first.',
    },
    {
      id: 'message-2',
      role: 'assistant',
      author: 'Pi',
      timestamp: '9:39 am',
      status: 'stable',
      markdown:
        'I have mapped the remaining work and started with the **authoritative product state**.\n\nThe conversation will stay readable while tools run, and every consequential action will wait for a confirmed decision.',
    },
    {
      id: 'message-3',
      role: 'assistant',
      author: 'Pi',
      timestamp: '9:41 am',
      status: 'streaming',
      markdown:
        'Building the conversation, activity and review surfaces now. The current draft remains available while this work continues.',
    },
  ],
  turnStatus: 'tool-running',
  queue: [
    {
      localId: 'queue-1',
      number: 1,
      text: 'Then review the light theme at compact width.',
      state: 'acknowledged',
    },
  ],
  activity: [
    {
      id: 'activity-1',
      category: 'search',
      verb: 'Reviewed',
      target: 'product requirements',
      state: 'complete',
      elapsed: '0.8s',
      summary: 'Mapped the required screens and recovery states.',
    },
    {
      id: 'activity-2',
      category: 'file',
      verb: 'Editing',
      target: 'conversation workspace',
      state: 'running',
      elapsed: '18s',
      summary: 'Applying the Luminous Graphite shell and typed state.',
    },
    {
      id: 'activity-3',
      category: 'command',
      verb: 'Waiting to run',
      target: 'release verification',
      state: 'waiting',
      elapsed: '—',
      summary: 'Verification will begin after the implementation batch is complete.',
    },
  ],
  approvals: [
    {
      id: 'approval-1',
      decisionId: 'decision-1',
      state: 'awaiting',
      action: 'Run the local verification suite',
      target: 'PIUI project',
      reason: 'Confirm the completed implementation builds and behaves as designed.',
      dataLeavingMac: 'Nothing. This check runs locally.',
      impact: 'Reads project files and creates local build output.',
      reversible: true,
      permittedDecisions: ['approve-once', 'deny'],
      rememberedScopeEligible: false,
    },
  ],
  changes: [
    {
      id: 'change-1',
      path: 'src/app/ProductionApp.tsx',
      state: 'added',
      additions: 148,
      deletions: 0,
      before: [],
      after: [
        "import { AppShell } from './AppShell';",
        '',
        'export function ProductionApp() {',
        '  return <AppShell />;',
        '}',
      ],
      undo: 'safe',
    },
    {
      id: 'change-2',
      path: 'src/styles/theme-dark.css',
      state: 'modified',
      additions: 42,
      deletions: 3,
      before: [':root {', '  --canvas: #090b0a;', '}'],
      after: [':root[data-theme="dark"] {', '  --canvas: #080a09;', '  --surface: #0f1210;', '}'],
      undo: 'revoked',
    },
  ],
  diagnostics: [
    { id: 'host', label: 'PIUI native host', status: 'pass', detail: 'Ready on Apple Silicon.' },
    {
      id: 'sidecar',
      label: 'Local Pi helper',
      status: 'pass',
      detail: 'Node 22 runtime and Pi 0.82.0 are available.',
    },
    {
      id: 'provider',
      label: 'Provider connection',
      status: 'pass',
      detail: 'ChatGPT / Codex subscription is connected.',
    },
    {
      id: 'keychain',
      label: 'Credential storage',
      status: 'pass',
      detail: 'Credentials are held by macOS Keychain.',
    },
    {
      id: 'updates',
      label: 'Public updates',
      status: 'offline',
      detail: 'Not run — release endpoint and verification key are not configured.',
    },
  ],
  resources: [
    {
      id: 'resource-1',
      kind: 'skill',
      name: 'code-review',
      version: '1.0.0',
      source: 'global',
      enabled: true,
      trusted: true,
      executable: false,
      description: 'A structured review guide.',
      operations: ['disable'],
    },
    {
      id: 'resource-2',
      kind: 'prompt',
      name: 'explain-changes',
      version: '1.1.0',
      source: 'project',
      enabled: true,
      trusted: true,
      executable: false,
      description: 'Summarises a completed change in plain language.',
      operations: ['disable'],
    },
    {
      id: 'resource-3',
      kind: 'theme',
      name: 'Luminous Graphite',
      version: '1.0.0',
      source: 'global',
      enabled: true,
      trusted: true,
      executable: false,
      description: 'PIUI’s signature dark presentation.',
      operations: ['disable'],
    },
    {
      id: 'resource-4',
      kind: 'extension',
      name: 'Example project extension',
      version: '0.4.0',
      source: 'project',
      enabled: false,
      trusted: false,
      executable: true,
      description: 'Executable project code. Disabled until explicitly trusted.',
      operations: ['enable'],
    },
    {
      id: 'resource-5',
      kind: 'package',
      name: 'Pi example package',
      version: '2.0.1',
      source: 'package',
      enabled: false,
      trusted: false,
      executable: true,
      description: 'Executable package. Disabled in Simple mode.',
      operations: ['enable', 'update', 'remove'],
    },
  ],
  update: {
    status: 'disabled',
    endpointConfigured: false,
    publicKeyConfigured: false,
    message:
      'Public updates are disabled until release hosting and a verification key are configured.',
  },
} as const);
