import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const run = spawnSync(
  'pnpm',
  ['exec', 'playwright', 'test', '--config', 'playwright.performance.config.ts'],
  { cwd: root, encoding: 'utf8', env: process.env },
);
process.stdout.write(run.stdout ?? '');
process.stderr.write(run.stderr ?? '');
if (run.status !== 0) process.exit(run.status ?? 1);
const match = (run.stdout ?? '').match(/PIUI_PERFORMANCE:(\{[^\n]+\})/u);
if (!match) throw new Error('Performance run produced no bounded metric record');
const metrics = JSON.parse(match[1]);
const report = `# PIUI local performance evidence

Generated by \`pnpm performance:report\` from the deterministic development-only product fixture. This is local, non-telemetric browser evidence; final public release measurements still require the supported packaged Apple Silicon app.

| Budget | Observed | Result |
| --- | ---: | --- |
| Warm launch p50 ≤ 2,000 ms | ${metrics.warmP50.toFixed(1)} ms | Pass |
| Warm launch p95 ≤ 3,000 ms | ${metrics.warmP95.toFixed(1)} ms | Pass |
| 10,000-message / approximately 50 MB scroll p95 < 50 ms | ${metrics.scrollP95.toFixed(1)} ms | Pass |
| Visible transcript DOM rows ≤ 500 | ${metrics.visibleRows} | Pass |
| JavaScript heap < 500 MB when exposed by Chromium | ${metrics.heapBytes > 0 ? `${(metrics.heapBytes / 1_048_576).toFixed(1)} MB` : 'Not exposed'} | ${metrics.heapBytes > 0 ? 'Pass' : 'Not run'} |
| Cancellation response ≤ 200 ms | ${metrics.cancellationMs} ms | Pass |
| Resize page overflow ≤ 1 px | ${metrics.resizeOverflowPx} px | Pass |

The browser suite also asserts every visible primary action is at least 44 × 44 CSS pixels and remains horizontally contained at 680 × 560.
`;
writeFileSync(resolve(root, '.forge/PERFORMANCE.md'), report, { encoding: 'utf8', flag: 'w' });
process.stdout.write('Wrote .forge/PERFORMANCE.md\n');
